packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@nestjs/core": true
  "@prisma/engines": true
  "@scarf/scarf": true
  "bcrypt": true
  "esbuild": true
  "lightningcss": true
  "lefthook": true
  "prisma": true
  "unrs-resolver": true
  "@weapp-tailwindcss/merge": true
  "weapp-tailwindcss": true

overrides:
  "@types/sass": "1.43.1"